version: "3.9"

services:
  mosquitto:
    build: ./mosquitto
    container_name: mosquitto
    restart: always
    networks:
      - stream-table-network
    ports:
      - "1883:1883"

  # obs-service: # dev mode
  #   build: ./obs-service
  #   container_name: obs-service
  #   restart: always
  #   networks:
  #     - stream-table-network

  web-app: # dev mode
    build: ./web-app
    container_name: web-app
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - game-service
    volumes:
      - ./web-app/public:/app/public
      - ./web-app/src:/app/src
    networks:
      - stream-table-network

  postgre:
    image: postgres:18.2-bookworm
    container_name: postgresql
    restart: always
    env_file:
      - ./postgresql/.env
    ports:
      - "5432:5432"
    volumes:
      - ./postgresql/postgres_data:/var/lib/postgresql
    networks:
      - stream-table-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

  game-service:
    env_file:
      - sample.env
    build: ./game-service
    container_name: game-service
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./game-service:/app # Used for dev
    depends_on:
      - mosquitto
      - postgre
    networks:
      - stream-table-network

volumes:
  postgres_data:

networks:
  stream-table-network:
    driver: bridge
