"""New db model for User

Revision ID: 18a1927e4957
Revises: c2e6d4bb5ec8
Create Date: 2026-08-11 17:49:41.202831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18a1927e4957'
down_revision: Union[str, Sequence[str], None] = 'c2e6d4bb5ec8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('status', sa.String(length=20), nullable=False))
    op.add_column('users', sa.Column('seat_number', sa.Integer(), nullable=True))
    op.alter_column('users', 'table_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'table_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('users', 'seat_number')
    op.drop_column('users', 'status')
    # ### end Alembic commands ###
